- grid:
  - Nodes:
      node:
        id: index
        u_rated: vn_kv
  - Cables:
      line:
        id: index
        from_node: from_bus
        from_status: in_service
        to_node: to_bus
        to_status: in_service
        r1: r_ohm_per_km
        x1: x_ohm_per_km
        c1: c_nf_per_km
        tan1: Not sure
        r0: r0_ohm_per_km
        x0: x0_ohm_per_km
        c0: c0_nf_per_km
        tan0: Not sure
        i_n: max_i_ka??
  - Links:
      link:
        id: No such thing as a link in PP
        from_node: nothing
        from_status: nothing
        to_node: nothing
        to_status: nothing
  - Reactance coils:
      line:
        id: No such thing as a reactance coil in PP
        from_node: nothing
        from_status: nothing
        to_node: nothing
        to_status: nothing
        r1: nothing
        x1: nothing
        c1: nothing
        tan1: nothing
        r0: nothing
        x0: nothing
        c0: nothing
        tan0: nothing
        i_n: nothing
        extra: nothing
  - Transformers:
      transformer:
        id: index
        from_node: hv_bus
        from_status: in_service
        to_node: lv_bus
        to_status: in_service
        u1: vn_hv_kv
        u2: vn_lv_kv
        sn: sn_mva
        uk: vk_percent
        pk: pfe_kw
        i0: not sure
        p0: not sure
        winding_from: hv_bus?
        winding_to: lv_bus?
        clock: shift_degree????
        tap_side: tap_side
        tap_pos: tap_neutral
        tap_min: tap_min
        tap_max: tap_max
        tap_nom: tap_pos
        tap_size: tap_step_percent or tap_step_degree??
        uk_min: not found
        uk_max: not found
        pk_min: not found
        pk_max: not found
        r_grounding_from: could be xn_ohm
        x_grounding_from: could be xn_ohm
        r_grounding_to: could be xn_ohm
        x_grounding_to: could be xn_ohm
  - Special transformers:
      transformer(copied from transformer):
        id: index
        from_node: hv_bus
        from_status: in_service
        to_node: lv_bus
        to_status: in_service
        u1: vn_hv_kv
        u2: vn_lv_kv
        sn: sn_mva
        uk: vk_percent
        pk: pfe_kw
        i0: not sure
        p0: not sure
        winding_from: hv_bus?
        winding_to: lv_bus?
        clock: shift_degree????
        tap_side: tap_side
        tap_pos: tap_neutral
        tap_min: tap_min
        tap_max: tap_max
        tap_nom: tap_pos
        tap_size: tap_step_percent or tap_step_degree??
        uk_min: not found
        uk_max: not found
        pk_min: not found
        pk_max: not found
        r_grounding_from: could be xn_ohm
        x_grounding_from: could be xn_ohm
        r_grounding_to: could be xn_ohm
        x_grounding_to: could be xn_ohm
  - Three-Winding Transformer:
      three-winding transformer:
        u1: hv_bus
        u2: mv_bus
        u3: lv_bus
        sn_1: vn_hv_kv
        sn_2: vn_mv_kv
        sn_3: vn_lv_kv
        uk_12: vk_hv_percent
        uk_13: vk_mv_percent
        uk_23: vk_lv_percent
        pk_12: not found
        pk_13: not found
        pk_23: not found
        i0: not found
        p0: pfe_kw
        winding_1: not found
        winding_2: not found
        winding_3: not found
        clock_12: not found
        clock_13: not found
        tap_side: tap_side
        tap_pos: tap_pos
        tap_min: tap_min
        tap_max: tap_max
        tap_nom: tap_neutral???
        tap_size: tap_step_percent or tap_step_degree
  - Loads:
      sym_load:
        id: index
        node: bus
        status: in_service
        type: type(Valid for three phase load flow only)
        p_specified: p_mw
        q_specified: q_mvar
  - Sources:
      source(External grid in PP?):
        id: Empty
        node: bus
        status: in_service
        u_ref: vm_pu
        sk: s_sc_max_mva or s_sc_min_mva
        rx_ratio: rx_max or rx_min
        z01_ratio: r0x0_max???
